routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;


// /* Create Syombolic Link Storage Callback */
// Route::get('/storage-link', function () {
//     Artisan::call('storage:link');
// });

/* Auth Verify */
Auth::routes(['verify' => true]);

Route::group(['middleware' => ['auth', 'verified', 'xss']], function()
{
    Route::get('/', 'HomeController@index');
    Route::get('/dashboard', 'HomeController@index')->name('home');
    Route::view('/test', 'auth.verify');
});

/* Admin Routes */
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['auth','xss']], function () {

    /* Category Routes */
    Route::resource('category', 'CategoryController');
    Route::get('category/edit/{id}', 'CategoryController@create')->name('category.edit');
    Route::get('category-list', 'CategoryController@list')->name('category.list');
    Route::delete('category/destroy/{id}', 'CategoryController@destroy')->name('category.destroy');

    /* Subcategory Routes */
    Route::get('subcategory/dropdown', 'SubCategoryController@getsubCategoryList')->name('subcategory.dropdown');
    Route::resource('subcategory','SubCategoryController');
    Route::get('subcategory-list', 'SubCategoryController@list')->name('subcategory.list');
    Route::get('subcategory/edit/{id}', 'SubCategoryController@create')->name('subcategory.edit');
    Route::delete('subcategory/destroy/{id}', 'SubCategoryController@destroy')->name('subcategory.destroy');

    /* Static Data */
    Route::resource('static-data', 'StaticDataController');
    Route::get('static-data/edit/{id}', 'StaticDataController@create')->name('static-data.edit');
    Route::get('static-data-list', 'StaticDataController@list')->name('static-data.list');
    Route::delete('static-data/destroy/{id}', 'StaticDataController@destroy')->name('static-data.destroy');

    /* Author Routes */
    Route::resource('author','AuthorController');
    Route::get('author-list/{type?}','AuthorController@dataList')->name('dataList');
    Route::get('author-list/edit/{id}','AuthorController@create')->name('author.edit');
    Route::get('author-view/{id}','AuthorController@show')->name('author.show');
    Route::delete('author/destroy/{id}','AuthorController@destroy')->name('author.destroy');

    /* Mobile Slider */
    Route::resource('mobileslider', 'MobileSliderController');
    Route::get('mobileslider-list', 'MobileSliderController@list')->name('mobileslider.list');
    Route::get('mobileslider/edit/{id}', 'MobileSliderController@create')->name('mobileslider.edit');
    Route::get('mobileslider/destroy/{id}', 'MobileSliderController@destroy')->name('mobileslider.destroy');

    /* Book Routes */
    Route::resource('book', 'BookController');
    Route::get('book-edit/{id?}','BookController@create')->name('book.update');
    Route::get('book-list/{type?}','BookController@bookList')->name('book.list');
    Route::get('book-view/{id}','BookController@view')->name('book.view');
    Route::get('book-destroy/{id}','BookController@destroy')->name('book.delete');
    Route::post('book-action','BookController@bookActions')->name('book.actions');

    /* Setting Routes */
    Route::get('privacy-policy','SettingController@privacyPolicy')->name('privacy-policy');
    Route::post('privacy-policy-save','SettingController@savePrivacyPolicy')->name('privacy-policy-save');
    Route::get('term-condition','SettingController@termAndCondition')->name('term-condition');
    Route::post('term-condition-save','SettingController@saveTermAndCondition')->name('term-condition-save');

    /* Feedback Routes */
    Route::get('users/feedback','UsersController@userFeedback')->name('users_feedback');
    Route::get('users/feedback/datalist','UsersController@userFeedbackDataList')->name('users_feedback.list');

    /* Sales Routes */
    Route::get('/transactions/list/{id?}/{record?}','TransactionController@list')->name('transactions.list');
    Route::resource('transactions','TransactionController');
    Route::get('update-payment-status/{id}/{status}','TransactionController@updatePaymentStatus')->name('transactions_update.payment_status');

    /* User Details Routes */
    Route::resource('users','UsersController');
    Route::get('user-list','UsersController@list')->name('user.list');
    Route::get('user-delete/{id}','UsersController@destroy')->name('user.delete');
    Route::post('/password/upadte', 'UsersController@passwordUpdate')->name('user.password.update');
    Route::post('/profile/save', 'UsersController@userUpdate')->name('user.update');

    /* Settings Routes */
    Route::get('settings', 'SettingController@settings')->name('admin.settings');
    Route::post('/layout-page', 'SettingController@layoutPage')->name('layout_page');
    Route::post('settings/save', 'SettingController@settingsUpdates')->name('settingsUpdates');
    Route::post('contact-us', 'SettingController@contactus_settings')->name('contactus_settings');
    Route::post('env-setting', 'SettingController@envSetting')->name('envSetting');
    Route::get('mobile-app','SettingController@getMobileSetting')->name('mobile_app.config');
    Route::post('mobile-app/save','SettingController@saveMobileSetting')->name('mobile_app.config.save');
});

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
// use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Book extends Model implements HasMedia
{
    use HasMediaTrait;

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
              ->width(315)
              ->height(315);
    }
    //book model
    // use SoftDeletes;
    protected $table="book";
    protected $primaryKey='book_id';
    protected $fillable=['category_id','subcategory_id','keywords','author_id','name','title','description','edition','keywords','language','publisher','date_of_publication','front_cover','back_cover','file_path','file_sample_path','format','status','check_mark','page_count','price','in_stock','flag_top_sell','flag_recommend','discount','discounted_price'];

    public function categoryName()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function subCategoryName()
    {
        return $this->belongsTo(SubCategory::class, 'subcategory_id');
    }

    public function getBookRating()
    {
        return $this->hasMany(BookRating::class, 'book_id')->with(['getUsername']);
    }

    public function getAuthor()
    {
        return $this->belongsTo(Author::class, 'author_id');
    }

    public function getBookLanguage()
    {
        return $this->belongsTo(StaticData::class,'language','id');
    }

    public function getAuthorBookList()
    {
        return $this->hasMany(Book::class, 'author_id','author_id');
    }

    public function getCategoryBookList()
    {
        return $this->hasMany(Book::class, 'category_id','category_id');
    }

    public function getWishList()
    {
        return $this->hasMany(UserWishlistBook::class, 'book_id','book_id');
    }

    public function getPurchase()
    {
        return $this->hasMany(TransactionDetail::class, 'book_id','book_id');
    }

    public function getAuthors()
    {
        return $this->hasMany(Author::class, 'author_id','author_id');
    }

    public function getUserBookRating()
    {
        // if(\Auth::user() != null){
        //     return $this->hasOne(BookRating::class, 'book_id')->filter('user_id',\Auth::user()->id);
        // }
        return null;
    }
}

app/Http/Controllers/API/Book/BookController.php
<?php

namespace App\Http\Controllers\API\Book;

use Illuminate\Http\Request;
use App\Book;
use App\BookRating;
use App\UserWishlistBook;
use App\Http\Controllers\Controller;
use App\Http\Resources\API\Book\BookResource;
use App\Http\Resources\API\Book\UserWishlistBookResource;
use App\Http\Resources\API\Book\BookDetailResource;
use App\Http\Resources\API\Book\BookRatingResource;
use App\Http\Resources\API\Author\AuthorResource;


class BookController extends Controller
{

    public function getBookList(Request $request){
        $book_data       =       Book::orderBy('book_id', 'DESC')
                                                ->with([
                                                        'getAuthor',
                                                        'categoryName',
                                                        'subCategoryName',
                                                        // 'isWishlistBook'
                                                    ]);

            if($request->has('category_id') && $request->category_id != null ){
                    $book_data->where('category_id',$request->category_id);
            }

            if($request->has('subcategory_id') && $request->subcategory_id != null ){
                $book_data->where('subcategory_id',$request->subcategory_id);
            }

            if($request->has('search_text') && $request->search_text != null){
                $book_data->orWhere('name', 'LIKE', '%'.$request->search_text.'%');
                $book_data->orWhere('title', 'LIKE', '%'.$request->search_text.'%');
            }

            if($request->has('author_id') && $request->author_id != null ){
                $book_data->where('author_id',$request->author_id);
            }

            if($request->has('min_price') && $request->min_price != null || $request->has('max_price') && $request->max_price != null){
                $book_data->having('price','>=',$request->min_price)->having('price','<=',$request->max_price);
            }

            if($request->has('rating') && $request->rating != null ){
                $book_data->where('rating',$request->rating);
            }

            $max               =  $book_data->max('price');
            $book_data  =  $book_data->paginate(12);

            $items        =   BookResource::collection($book_data);
            $response = [
                        'pagination' => [
                                                'total_items' => $items->total(),
                                                'per_page' => $items->perPage(),
                                                'currentPage' => $items->currentPage(),
                                                'totalPages' => $items->lastPage(),
                                                'from' => $items->firstItem(),
                                                'to' => $items->lastItem(),
                                                'next_page'=>$items->nextPageUrl(),
                                                'previous_page'=>$items->previousPageUrl(),
                                            ],
                        'data' => $items,
                        'max_price'=> $max

                    ];
            return response()->json($response);

    }

    public function getBookDetail(Request $request){
        $book_data =     Book::where('book_id', $request->book_id)
                                                    ->with([
                                                        'categoryName',
                                                        'subCategoryName',
                                                        'getAuthors',
                                                        'getAuthorBookList',
                                                        'getCategoryBookList',
                                                        'getBookRating',
                                                        'getWishList',
                                                        'getPurchase'
                                                    ])
                                                    ->get();
        $getBookDetail                    =   BookDetailResource::collection($book_data);
        $getBookRating                   =   BookRatingResource::collection($book_data[0]->getBookRating);
        $getAuthorBookList           =   BookResource::collection($book_data[0]->getAuthorBookList);
        $getCategoryBookList       =   BookResource::collection($book_data[0]->getCategoryBookList);
        $getUserReview                   =  Null;
        $getAuthorDetail                 = AuthorResource::collection($book_data[0]->getAuthors);


        if($request->user_id != null){
            $getUserReview          =    BookRating::where('user_id',$request->user_id)->where('book_id',$request->book_id)->first();
        }

        $response = [
                'book_detail' => $getBookDetail,
                'author_detail' =>$getAuthorDetail,
                'author_book_list' => $getAuthorBookList,
                'recommended_book'=>$getCategoryBookList,
                'book_rating_data'=>$getBookRating,
                'user_review_data'=>$getUserReview
        ];

        return response()->json($response);
    }

    // Rating Module
    public function addBookRating(Request $request){
        $data = $request->all();

        $user  = \Auth::user();
        $data['user_id'] = $user->id;

        $result = BookRating::Create($data);
        $message = trans('messages.save_form',['form' => 'Book Rating']);

        return response()->json([ 'status' => true ,'message' => $message ]);
    }

    public function updateBookRating(Request $request){
        $data = $request->all();

        $user  = \Auth::user();
        $data['user_id'] = $user->id;

        $result = BookRating::where('rating_id',$request->rating_id)->Update($data);
        $message = trans('messages.update_form',['form' => 'Book Rating']);

        return response()->json([ 'status' => true ,'message' => $message ]);
    }

    public function getBookRating(Request $request){

        $rating_data = BookRating::where('book_id',$request->book_id)->get();
        return  BookRatingResource::collection($rating_data);
    }

    public function deleteBookRating(Request $request){
        $user = \Auth::user();

        $book_rating = BookRating::where('rating_id',$request->id)->where('user_id',$user->id)->delete();

        $message = trans('messages.delete_form',['form' => 'Book Rating']);

        return response()->json([ 'status' => true ,'message' =>$message ]);
    }

    public function getUserWishlistBook(){
        $user = \Auth::user();
        $user_id = $user->id;
        $data = UserWishlistBook::where('user_id',$user_id)
                                ->orderBy('wishlist_id', 'DESC')
                                ->with([
                                    'getBook'
                                ])
                                ->get();
        $wishlist_data =  UserWishlistBookResource::collection($data);
        return response()->json(['status' => true ,'data' => $wishlist_data]);

    }

    public function addRemoveWishlistBook(Request $request){
        $user   = \Auth::user();
        $id     = isset($request->id) ? $request->id : '';

        $data   = $request->all();
        $data['user_id'] = $user->id;

        if($request->is_wishlist == 0){
            UserWishlistBook::where('book_id',$data['book_id'])->where('user_id',$data['user_id'])->delete();
            $message = trans('messages.removed_in_wishlist');
        }else{
            UserWishlistBook::Create($data);
            $message = trans('messages.added_in_wishlist');
        }

        return response()->json([ 'status' => true ,'message' => $message ]);
    }
}

resources/views/Admin/book/index.blade.php
@extends('layouts.master')

@section('content')
<link href="{{ asset('/plugin/tooltip/tooltip-flip.css') }}" rel="stylesheet" type="text/css" />

<div id="newapp" class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3 class="d-inline">{{ isset($pageTitle) ? $pageTitle: trans('messages.list') }}</h3>
                @if(!in_array($type, ["recommended",'top-sell']))
                    <a class="btn btn-sm btn-primary float-right d-inline" href="{{ route('book.create') }}">
                        <i class="fa fa-plus-circle"></i> 
                        {{ trans('messages.add_button_form', ['form' => trans('messages.book')]) }}
                    </a>
                @endif
            </div>
            <div class="card-body">
                <div class="card-block pall-10 text-center">
                    <div class="col-md-12">
                        @if($type == "recommended")
                            <data-table class="table table-responsive-sm md-responsive" ajax="{{ route('book.list', ['type' => $type]) }}" :columns="[
                                {data: 'DT_RowIndex','searchable':false, name: 'DT_RowIndex', title : '{{ trans('messages.srno') }}','orderable' : false },
                                {data: 'front_cover'  ,'name' : 'front_cover' ,'title' : '{{ trans('messages.image') }}','type' : 'image'},
                                {data: 'name'    ,'name' : 'name'  ,'title' : '{{ trans('messages.field_name',['field' => trans('messages.book')]) }}'},
                                {data: 'author_name'    ,'name' : 'getAuthor.name'  ,'title' : '{{ trans('messages.author') }}'},
                                {data: 'category_name' ,'name' : 'categoryName.name'  ,'title' : '{{ trans('messages.field_name',['field' => trans('messages.category')]) }}'},
                                {data: 'flag_recommend'    ,'name' : 'flag_recommend'  ,'title' : '{{ trans('messages.recommended_book') }}'},
                                {data: 'action'       ,'name' : 'action'     ,'title' : '{{ trans('messages.action') }}',orderable : false,'searchable':false},
                            ]">
                            </data-table>
                        @elseif($type == "top-sell")
                            <data-table class="table table-responsive-sm md-responsive" ajax="{{ route('book.list', ['type' => $type]) }}" :columns="[
                                {data: 'DT_RowIndex','searchable':false, name: 'DT_RowIndex', title : '{{ trans('messages.srno') }}','orderable' : false },
                                {data: 'front_cover'  ,'name' : 'front_cover' ,'title' : '{{ trans('messages.image') }}','type' : 'image'},
                                {data: 'name'    ,'name' : 'name'  ,'title' : '{{ trans('messages.field_name',['field' => trans('messages.book')]) }}'},
                                {data: 'author_name'    ,'name' : 'getAuthor.name'  ,'title' : '{{ trans('messages.author') }}'},
                                {data: 'category_name' ,'name' : 'categoryName.name'  ,'title' : '{{ trans('messages.field_name',['field' => trans('messages.category')]) }}'},
                                {data: 'flag_top_sell'    ,'name' : 'flag_top_sell'  ,'title' : '{{ trans('messages.top_selling_book') }}'},
                                {data: 'action'       ,'name' : 'action'     ,'title' : '{{ trans('messages.action') }}',orderable : false,'searchable':false},
                                ]">
                            </data-table>
                        @else
                            <data-table class="table table-responsive" ajax="{{ route('book.list',['type' => $type]) }}" :columns="[
                                {data: 'DT_RowIndex','searchable':false, name: 'DT_RowIndex', title : '{{ trans('messages.srno') }}','orderable' : false },
                                {data: 'front_cover'  ,'name' : 'front_cover' ,'title' : '{{ trans('messages.image') }}','type' : 'image'},
                                {data: 'name'    ,'name' : 'name'  ,'title' : '{{ trans('messages.field_name',['field' => trans('messages.book')]) }}'},
                                {data: 'author_name'    ,'name' : 'getAuthor.name'  ,'title' : '{{ trans('messages.author') }}'},
                                {data: 'category_name' ,'name' : 'categoryName.name'  ,'title' : '{{ trans('messages.field_name',['field' => trans('messages.category')]) }}'},
                                {data: 'flag_top_sell'    ,'name' : 'flag_top_sell'  ,'title' : '{{ trans('messages.top_selling_book') }}'},
                                {data: 'flag_recommend'    ,'name' : 'flag_recommend'  ,'title' : '{{ trans('messages.recommended_book') }}'},
                                {data: 'action'       ,'name' : 'action'     ,'title' : '{{ trans('messages.action') }}',orderable : false,'searchable':false},
                                ]">
                            </data-table>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('body_bottom')
<script>
    function addChapter(id) {
        $('#chaptermodal').modal('show');
    }

    function bookActions(ele,postData) {
        var loadurl = "{{ route('book.actions') }}";
        $.post(loadurl,postData ,function(data) {
            if(data.status == true && data.message!=''){
                showMessage(data.message);
            }
        });

        return true;
    }

    $(document).ready(function() {
        $("#addmore").click(function () {
            $('#fieldsrow').clone().insertAfter(this);
        });
        $(document).on('click',".flag_recommend_toggle",function (event) {
            if($(this).is(":checked")){
                var postData = {'book_id':$(this).val(),'flag_recommend':1,'event':'add'};
            }else{
                var postData = {'book_id':$(this).val(),'flag_recommend':0};
            }
            bookActions($(this),postData);
        });
        $(document).on('click',".flag_top_sell_toggle",function (event) {
            if($(this).is(":checked")){
                var postData = {'book_id':$(this).val(),'flag_top_sell':1,'event':'add'};
            }else{
                var postData = {'book_id':$(this).val(),'flag_top_sell':0};
            }
            bookActions($(this),postData);
        });
    });
</script>
@endsection