routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;


// /* Create Syombolic Link Storage Callback */
// Route::get('/storage-link', function () {
//     Artisan::call('storage:link');
// });

/* Auth Verify */
Auth::routes(['verify' => true]);

Route::group(['middleware' => ['auth', 'verified', 'xss']], function()
{
    Route::get('/', 'HomeController@index');
    Route::get('/dashboard', 'HomeController@index')->name('home');
    Route::view('/test', 'auth.verify');
});

/* Admin Routes */
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['auth','xss']], function () {

    /* Category Routes */
    Route::resource('category', 'CategoryController');
    Route::get('category/edit/{id}', 'CategoryController@create')->name('category.edit');
    Route::get('category-list', 'CategoryController@list')->name('category.list');
    Route::delete('category/destroy/{id}', 'CategoryController@destroy')->name('category.destroy');

    /* Subcategory Routes */
    Route::get('subcategory/dropdown', 'SubCategoryController@getsubCategoryList')->name('subcategory.dropdown');
    Route::resource('subcategory','SubCategoryController');
    Route::get('subcategory-list', 'SubCategoryController@list')->name('subcategory.list');
    Route::get('subcategory/edit/{id}', 'SubCategoryController@create')->name('subcategory.edit');
    Route::delete('subcategory/destroy/{id}', 'SubCategoryController@destroy')->name('subcategory.destroy');

    /* Static Data */
    Route::resource('static-data', 'StaticDataController');
    Route::get('static-data/edit/{id}', 'StaticDataController@create')->name('static-data.edit');
    Route::get('static-data-list', 'StaticDataController@list')->name('static-data.list');
    Route::delete('static-data/destroy/{id}', 'StaticDataController@destroy')->name('static-data.destroy');

    /* Author Routes */
    Route::resource('author','AuthorController');
    Route::get('author-list/{type?}','AuthorController@dataList')->name('dataList');
    Route::get('author-list/edit/{id}','AuthorController@create')->name('author.edit');
    Route::get('author-view/{id}','AuthorController@show')->name('author.show');
    Route::delete('author/destroy/{id}','AuthorController@destroy')->name('author.destroy');

    /* Mobile Slider */
    Route::resource('mobileslider', 'MobileSliderController');
    Route::get('mobileslider-list', 'MobileSliderController@list')->name('mobileslider.list');
    Route::get('mobileslider/edit/{id}', 'MobileSliderController@create')->name('mobileslider.edit');
    Route::get('mobileslider/destroy/{id}', 'MobileSliderController@destroy')->name('mobileslider.destroy');

    /* Book Routes */
    Route::resource('book', 'BookController');
    Route::get('book-edit/{id?}','BookController@create')->name('book.update');
    Route::get('book-list/{type?}','BookController@bookList')->name('book.list');
    Route::get('book-view/{id}','BookController@view')->name('book.view');
    Route::get('book-destroy/{id}','BookController@destroy')->name('book.delete');
    Route::post('book-action','BookController@bookActions')->name('book.actions');

    /* Setting Routes */
    Route::get('privacy-policy','SettingController@privacyPolicy')->name('privacy-policy');
    Route::post('privacy-policy-save','SettingController@savePrivacyPolicy')->name('privacy-policy-save');
    Route::get('term-condition','SettingController@termAndCondition')->name('term-condition');
    Route::post('term-condition-save','SettingController@saveTermAndCondition')->name('term-condition-save');

    /* Feedback Routes */
    Route::get('users/feedback','UsersController@userFeedback')->name('users_feedback');
    Route::get('users/feedback/datalist','UsersController@userFeedbackDataList')->name('users_feedback.list');

    /* Sales Routes */
    Route::get('/transactions/list/{id?}/{record?}','TransactionController@list')->name('transactions.list');
    Route::resource('transactions','TransactionController');
    Route::get('update-payment-status/{id}/{status}','TransactionController@updatePaymentStatus')->name('transactions_update.payment_status');

    /* User Details Routes */
    Route::resource('users','UsersController');
    Route::get('user-list','UsersController@list')->name('user.list');
    Route::get('user-delete/{id}','UsersController@destroy')->name('user.delete');
    Route::post('/password/upadte', 'UsersController@passwordUpdate')->name('user.password.update');
    Route::post('/profile/save', 'UsersController@userUpdate')->name('user.update');

    /* Settings Routes */
    Route::get('settings', 'SettingController@settings')->name('admin.settings');
    Route::post('/layout-page', 'SettingController@layoutPage')->name('layout_page');
    Route::post('settings/save', 'SettingController@settingsUpdates')->name('settingsUpdates');
    Route::post('contact-us', 'SettingController@contactus_settings')->name('contactus_settings');
    Route::post('env-setting', 'SettingController@envSetting')->name('envSetting');
    Route::get('mobile-app','SettingController@getMobileSetting')->name('mobile_app.config');
    Route::post('mobile-app/save','SettingController@saveMobileSetting')->name('mobile_app.config.save');
});

app/Mobile_slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Mobile_slider extends Model implements HasMedia
{
    use HasMediaTrait, SoftDeletes;
    
    protected $table="mobile_slider";
    protected $primaryKey='mobile_slider_id';
    protected $fillable=['title','slide_image','link'];
}

app/Http/Controllers/Admin/MobileSliderController.php
<?php

namespace App\Http\Controllers\Admin;;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\URL;
use App\Mobile_slider;
use DataTables;
use Yajra\DataTables\Html\Builder;

class MobileSliderController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $auth_user = authSession();
        if($auth_user->is('user') || $auth_user->is('sub_admin'))
        {
            return redirect()->route('home')->withSuccess(trans('messages.user_permission_denied'));
        }

        $pageTitle = trans('messages.list_form_title', ['form' => trans('messages.mobileslider_image')  ]);
        
        return view('Admin.mobile_slider.index', compact('pageTitle'));
    }

    public function list(Request $request)
    {
        $auth_user = authSession();
        if($auth_user->is('user') || $auth_user->is('sub_admin'))
        {
            return redirect()->route('home')->withSuccess(trans('messages.user_permission_denied'));
        }

        $query = Mobile_slider::orderBy('mobile_slider_id', 'DESC')->get() ;
        return Datatables::of($query)
        ->addColumn('slide_image', function ($query) {
            // $default=\URL::asset(\Config::get('constant.DEFAULT_IMAGE'));
            // $image = $default;
            // if(isset($query->slide_image)){
            //     $image=fileExitsCheck($default,'uploads/mobile_slider',$query->slide_image);
            // }
            // return "<img src='".$image."'border='0' width='80' class='img-rounded'>";
            return "<img src='".getSingleMedia($query, 'slide_image', null)."' border='0' width='80' class='img-rounded'>";
        })
        ->editColumn('action', function ($query) {
            return '
           
            <a class="btn btn-sm btn-primary" title = "'.trans('messages.edit') .'"
                href="'.route('mobileslider.edit', ['id' => $query->mobile_slider_id]).'">
                <i class="fa fa-edit "></i>
            </a>
            <a onclick="return confirm(\'Are you sure?\')" class="btn btn-sm btn-danger" title = "'.trans('messages.delete') .'"
                href="'.route('mobileslider.destroy', ['id' => $query->mobile_slider_id]).'">
              <i class="fa fa-trash"></i>
            </a>
            ';
        })
        ->rawColumns(['action', 'sr_no', 'slide_image'])
        ->addIndexColumn()
        ->toJson();
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id = -1)
    {
        $auth_user = authSession();
        if($auth_user->is('user') || $auth_user->is('sub_admin'))
        {
            return redirect()->route('home')->withSuccess(trans('messages.user_permission_denied'));
        }

        if($id != -1)
        {
            $pageTitle = trans('messages.update_form_title', ['form' => trans('messages.mobileslider_image')]);
            $slider_data = Mobile_slider::where('mobile_slider_id',$id)->first();
        }
        else
        {
            $pageTitle = trans('messages.add_button_form', ['form' => trans('messages.mobileslider_image')]);
            $slider_data = new Mobile_slider;
        }

        return view('Admin.mobile_slider.create', compact('slider_data', 'pageTitle'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $auth_user = authSession();
        if($auth_user->is('user') || $auth_user->is('sub_admin'))
        {
            return redirect()->route('home')->withSuccess(trans('messages.user_permission_denied'));
        }

        $data = $request->all();
        
        if($data['mobile_slider_id'] == null)
        {
            $validator = Validator::make($data, [
                'slide_image'=> 'required|mimetypes:image/jpeg,image/png,image/jpg,image/gif',
                ], ['Image should be png/PNG, jpg/JPG']
            );
        }
        else
        {
            $validator = Validator::make($data, [
                'slide_image'=> 'mimetypes:image/jpeg,image/png,image/jpg,image/gif',
                ], ['Image should be png/PNG, jpg/JPG']
            );
        }
        if($validator->fails())
        {
            return redirect()->back()->withInput()->withErrors($validator);
        }
        if($request->slide_image != null )
        {
            $image = uploadFile($request->slide_image,'/uploads/mobile_slider/');
            $data['slide_image'] = $image;
        }
        $result = Mobile_slider::updateOrCreate(['mobile_slider_id' => $request->mobile_slider_id],$data);
        if($request->slide_image != null )
        {
            $result->clearMediaCollection('slide_image');
            // $result->addMediaFromRequest('slide_image')
            //         ->toMediaCollection('slide_image');
        }
        $message = trans('messages.update_form', ['form' => trans('messages.mobileslider_image')]);
        if($result->wasRecentlyCreated)
        {
            $message = trans('messages.save_form', ['form' => trans('messages.mobileslider_image')]);
        }

        return redirect(route('mobileslider.index'))->withSuccess($message);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $auth_user = authSession();
        if($auth_user->is('user') || $auth_user->is('sub_admin'))
        {
            return redirect()->route('home')->withSuccess(trans('messages.user_permission_denied'));
        }

        $slider_image = Mobile_slider::where('mobile_slider_id', $id)->first();

        if(empty($slider_image))
        {
            $message = trans('messages.not_found_entry', ['form' => trans('messages.mobileslider_image')]);
        }
        else
        {
            $slider_image->clearMediaCollection('slide_image');
            $slider_image->delete();
            $message = trans('messages.delete_form', ['form' => trans('messages.mobileslider_image')]);
        }

        return redirect(route('mobileslider.index'))->withSuccess($message);
    }
}

resources/views/Admin/mobile_slider/create.blade.php
@extends('layouts.master')

@section('content')
<div class="col-md-6 offset-md-3">
    <div class="card">
        <div class="card-header">
            <h3 class="d-inline">{{ isset($pageTitle) ? $pageTitle : trans('messages.list') }}</h3>
            <a href="{{ route('mobileslider.index') }}" class="btn btn-sm btn-primary float-right d-inline">
                <i class="fa fa-angle-double-left"></i>
                {{ trans('messages.back') }}
            </a>
        </div>
        <div class="card-block pall-10">
            {!! Form::model($slider_data, ['route' => 'mobileslider.store', 'files' => true]) !!}
            {!! Form::hidden('mobile_slider_id', isset($slider_data->mobile_slider_id) ? $slider_data->mobile_slider_id : '') !!}
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            {!! Form::label('image',trans('messages.image')." *", array('class' => 'form-control-label')) !!}
                            <div class="custom-file">
                                {!! Form::file('slide_image', ['accept' => 'image/*', 'class' => 'custom-file-input custom-file-input-sm detail', 'onchange' => "readURL(this);"]) !!}
                                {!! Form::label('Image', isset($slider_data->slide_image)?$slider_data->slide_image:'', array('id' => 'imagelabel', 'class' => 'custom-file-label')) !!}
                                <div class="help-block with-errors"></div>  
                            </div>
                        </div>   
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <img id="slider_image" src="{{ getSingleMedia($slider_data, 'slide_image', null) }}" class="img w-75 h-50 img-responisve image d-block mb-20">
                    </div>
                </div> 
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            {!! Form::submit(trans('messages.save'), ['class' => 'btn btn-md btn-success pull-right']) !!}
                        </div>
                    </div>
                </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

@section('body_bottom')
<script>
    function readURL(input) {
        if(input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#slider_image').attr('src', e.target.result);
                $("#imagelabel").text((input.files[0].name));
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
@endsection

resources/views/Admin/mobile_slider/index.blade.php
@extends('layouts.master')

@section('content')
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h3 class="d-inline">{{ isset($pageTitle) ? $pageTitle : "List" }}</h3>
            <a class="btn btn-sm btn-primary float-right d-inline" href="{{ route('mobileslider.create') }}" title="{{ trans('messages.add_button_form', ['form' => trans('messages.mobileslider_image')]) }}">
                <i class="fa fa-plus-circle"></i>
                {{ trans('messages.add_button_form', ['form' => trans('messages.mobileslider_image')]) }}
            </a>
        </div>
        <div class="card-body">
            <div class="card-block p-2">
                <div class="row" id='newapp'>
                    <div class="col-md-12">
                        <data-table class="table text-center table-responsive-sm md-responsive"  ajax="{{ route('mobileslider.list') }}" :columns="[
                            {data: 'DT_RowIndex', name: 'DT_RowIndex', title : '{{ trans('messages.srno') }}','orderable' : 'false' },
                            {data: 'slide_image' ,'name': 'slide_image' , 'title' :'{{ trans('messages.image')}}'},
                            {data: 'action', name: 'action',title : '{{ trans('messages.action') }}',orderable : false},
                        ]">
                        </data-table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection